# Generated by Django 2.1 on 2018-08-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='id',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
